livereload: true

# Site settings
title: Jorge Serrano – Music Composer
email: hello@jorgeserranomusic.com
baseurl: "" # the subpath of your site, e.g. /news
baseurl_news: "/blog" # the subpath of the news
url: "https://jorgeserranomusic.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Jorge Serrano
twitter: JorgeSerrano_MC
instagram: jorgeserrano_music
spotify: 7GK7kNGjKLYpV70rXV3vdy
youtube: jorgeserrano_music
apple_music: jorge-serrano/1644328882

# Custom Settings
timezone: Europe/Madrid
permalink: /:categories/:title/

# Build settings
markdown: kramdown
incremental: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:
  - 404.html
